sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  - DB=postgresql
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database bookstore_test;' -U postgres
  - psql -c "CREATE USER bookstore WITH PASSWORD 'qwerty';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE bookstore_test TO bookstore;" -U postgres
bundler_args: --binstubs=./bundler_stubs