sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  - DB=postgresql
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec spec/
before_script:
  - gem install rake -v '12.0.0'
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml