## Customize the test machine
machine:

  ruby:
    version:
      2.4.1
dependencies:
  pre:
    - gem uninstall bundler # use a custom version of bundler
    - gem install bundler --pre

## Customize database setup
database:
  override:
    # replace CircleCI's generated database.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake db:create db:schema:load

## Customize test commands
test:
  override:
    - bundle exec rspec