## Customize the test machine
machine:

  ruby:
    version:
      2.4.1

  environment:

dependencies:
  override:
    - mv config/secrets.ci.yml config/secrets.yml

## Customize database setup
database:
  override:
    # replace CircleCI's generated database.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake db:create db:schema:load

## Customize test commands
test:
  override:
    - bundle exec rspec