version: 2
dependencies:
  pre:
    - bin/rails secrets:setup
    - gem install bundler
jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
        enviroment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: bookstore
          DEVISE_SECRET: 'f586be2b0c5a68d8065fa6937e1559130304d8111850e74c3bdd5dbf6959f2044cd77987b085c9ffdc1149bbb75dab221403028c4a0af0a1f6e220418d4acbff'
          DEVISE_FACEBOOK_APP_ID: '118440512125189'
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: bookstore
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: "qwerty"
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: rails-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results